version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/react-app
permissions:
  - object: /var/www/react-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
