version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:203918887881:task-definition/react-app-task:1"
        LoadBalancerInfo:
          ContainerName: "react-container"
          ContainerPort: 80

