version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - IMAGE_TAG=$(date +%s)

  build:
    commands:
      - echo "Building Docker Image..."
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
      - echo "Pushing Image to ECR..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"app-container","imageUri":"%s"}]' $ECR_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Updating task definition file..."
      - sed -i "s|<IMAGE_NAME>|$ECR_REPOSITORY_URI:$IMAGE_TAG|g" taskdef.json

artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yml
