version: 0.2

env:
  variables: 
    AWS_REGION: "us-east-1"
    ECR_REPOSITORY_URI: "203918887881.dkr.ecr.us-east-1.amazonaws.com/ecs-ec2-rolling"
phases:
  pre_build:
    commands:
      - echo "Retrieving Docker credentials..."
      - export DOCKER_USER=$(aws secretsmanager get-secret-value --secret-id docker-credentials --query SecretString --output text | jq -r '.username')
      - export DOCKER_PASS=$(aws secretsmanager get-secret-value --secret-id docker-credentials --query SecretString --output text | jq -r '.password')
      - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - export IMAGE_TAG=$(date +%s)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY_URI:$IMAGE_TAG $ECR_REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:latest
      - echo "Writing image definitions file..."
      - printf '[{"name":"react-app","imageUri":"%s"}]' "$ECR_REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
