version: 0.2

env:
  variables:
    ECR_REPOSITORY: "203918887881.dkr.ecr.us-east-1.amazonaws.com/react-app"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Fetching Docker credentials from Secrets Manager..."
      - DOCKER_SECRET=$(aws secretsmanager get-secret-value --secret-id docker-credentials --query SecretString --output text)
      - export DOCKER_USER=$(echo "$DOCKER_SECRET" | jq -r '.username')
      - export DOCKER_PASS=$(echo "$DOCKER_SECRET" | jq -r '.password')
      - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 203918887881.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t react-app .
      - docker tag react-app:latest $ECR_REPOSITORY:$IMAGE_TAG
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"app-container","imageUri":"%s"}]' "$ECR_REPOSITORY:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $ECR_REPOSITORY:$IMAGE_TAG
      - echo "Build and push completed successfully."

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
